//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace CinecanvasTest_Console
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    [System.Xml.Serialization.XmlRootAttribute("SubtitleReel", Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST", IsNullable = false)]
    public partial class SubtitleReelType {

        private string idField;

        private UserText contentTitleTextField;

        private UserText annotationTextField;

        private System.DateTime issueDateField;

        private string reelNumberField;

        private string languageField;

        private string editRateField;

        private string timeCodeRateField;

        private string startTimeField;

        private scopedTokenType displayTypeField;

        private SubtitleReelTypeLoadFont[] loadFontField;

        private object[] subtitleListField;

        public SubtitleReelType() {
            this.languageField = "en";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public UserText ContentTitleText {
            get {
                return this.contentTitleTextField;
            }
            set {
                this.contentTitleTextField = value;
            }
        }

        /// <remarks/>
        public UserText AnnotationText {
            get {
                return this.annotationTextField;
            }
            set {
                this.annotationTextField = value;
            }
        }

        /// <remarks/>
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string ReelNumber {
            get {
                return this.reelNumberField;
            }
            set {
                this.reelNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }

        /// <remarks/>
        public string EditRate {
            get {
                return this.editRateField;
            }
            set {
                this.editRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string TimeCodeRate {
            get {
                return this.timeCodeRateField;
            }
            set {
                this.timeCodeRateField = value;
            }
        }

        /// <remarks/>
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }

        /// <remarks/>
        public scopedTokenType DisplayType {
            get {
                return this.displayTypeField;
            }
            set {
                this.displayTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LoadFont")]
        public SubtitleReelTypeLoadFont[] LoadFont {
            get {
                return this.loadFontField;
            }
            set {
                this.loadFontField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Font", typeof(SubtitleReelTypeFont), IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Subtitle", typeof(SubtitleType), IsNullable = false)]
        public object[] SubtitleList {
            get {
                return this.subtitleListField;
            }
            set {
                this.subtitleListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class UserText {

        private string languageField;

        private string valueField;

        public UserText() {
            this.languageField = "en";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "language")]
        [System.ComponentModel.DefaultValueAttribute("en")]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class ImageType {

        private ImageTypeHalign halignField;

        private decimal hpositionField;

        private ImageTypeValign valignField;

        private decimal vpositionField;

        private string valueField;

        public ImageType() {
            this.halignField = ImageTypeHalign.center;
            this.hpositionField = ((decimal)(0m));
            this.valignField = ImageTypeValign.center;
            this.vpositionField = ((decimal)(0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ImageTypeHalign.center)]
        public ImageTypeHalign Halign {
            get {
                return this.halignField;
            }
            set {
                this.halignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Hposition {
            get {
                return this.hpositionField;
            }
            set {
                this.hpositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ImageTypeValign.center)]
        public ImageTypeValign Valign {
            get {
                return this.valignField;
            }
            set {
                this.valignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Vposition {
            get {
                return this.vpositionField;
            }
            set {
                this.vpositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum ImageTypeHalign {

        /// <remarks/>
        center,

        /// <remarks/>
        left,

        /// <remarks/>
        right,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum ImageTypeValign {

        /// <remarks/>
        center,

        /// <remarks/>
        bottom,

        /// <remarks/>
        top,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class RotateType {

        private RotateTypeDirection directionField;

        private string valueField;

        public RotateType() {
            this.directionField = RotateTypeDirection.none;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RotateTypeDirection.none)]
        public RotateTypeDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum RotateTypeDirection {

        /// <remarks/>
        none,

        /// <remarks/>
        left,

        /// <remarks/>
        right,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class SpaceType {

        private decimal sizeField;

        private string valueField;

        public SpaceType() {
            this.sizeField = ((decimal)(0.5m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.5")]
        public decimal Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class RubyType {

        private string rbField;

        private RubyTypeRT rtField;

        /// <remarks/>
        public string Rb {
            get {
                return this.rbField;
            }
            set {
                this.rbField = value;
            }
        }

        /// <remarks/>
        public RubyTypeRT Rt {
            get {
                return this.rtField;
            }
            set {
                this.rtField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class RubyTypeRT {

        private decimal sizeField;

        private RubyTypeRTPosition positionField;

        private decimal offsetField;

        private decimal spacingField;

        private decimal aspectAdjustField;

        private string valueField;

        public RubyTypeRT() {
            this.sizeField = ((decimal)(0.5m));
            this.positionField = RubyTypeRTPosition.before;
            this.offsetField = ((decimal)(0.0m));
            this.spacingField = ((decimal)(0.0m));
            this.aspectAdjustField = ((decimal)(1.0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.5")]
        public decimal Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RubyTypeRTPosition.before)]
        public RubyTypeRTPosition Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal Spacing {
            get {
                return this.spacingField;
            }
            set {
                this.spacingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
        public decimal AspectAdjust {
            get {
                return this.aspectAdjustField;
            }
            set {
                this.aspectAdjustField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum RubyTypeRTPosition {

        /// <remarks/>
        before,

        /// <remarks/>
        after,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class FontType {

        private FontTypeScript scriptField;

        private FontTypeEffect effectField;

        private FontTypeItalic italicField;

        private FontTypeUnderline underlineField;

        private FontTypeWeight weightField;

        private string idField;

        private byte[] colorField;

        private byte[] effectColorField;

        private string sizeField;

        private decimal aspectAdjustField;

        private decimal spacingField;

        private string[] textField;

        public FontType() {
            this.scriptField = FontTypeScript.normal;
            this.effectField = FontTypeEffect.shadow;
            this.italicField = FontTypeItalic.no;
            this.underlineField = FontTypeUnderline.no;
            this.weightField = FontTypeWeight.normal;
            this.sizeField = "42";
            this.aspectAdjustField = ((decimal)(1.0m));
            this.spacingField = ((decimal)(0.0m));
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontTypeScript.normal)]
        public FontTypeScript Script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontTypeEffect.shadow)]
        public FontTypeEffect Effect {
            get {
                return this.effectField;
            }
            set {
                this.effectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontTypeItalic.no)]
        public FontTypeItalic Italic {
            get {
                return this.italicField;
            }
            set {
                this.italicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontTypeUnderline.no)]
        public FontTypeUnderline Underline {
            get {
                return this.underlineField;
            }
            set {
                this.underlineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FontTypeWeight.normal)]
        public FontTypeWeight Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='FFFFFFFF' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
        public byte[] Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: DefaultValue attribute on members of type System.Byte[] is not supported in this version of the .Net Framework.
        // CODEGEN Warning: 'default' attribute on items of type 'hexBinary' is not supported in this version of the .Net Framework.  Ignoring default='FF000000' attribute.
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "hexBinary")]
        public byte[] EffectColor {
            get {
                return this.effectColorField;
            }
            set {
                this.effectColorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("42")]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
        public decimal AspectAdjust {
            get {
                return this.aspectAdjustField;
            }
            set {
                this.aspectAdjustField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal Spacing {
            get {
                return this.spacingField;
            }
            set {
                this.spacingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum FontTypeScript {

        /// <remarks/>
        normal,

        /// <remarks/>
        super,

        /// <remarks/>
        sub,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum FontTypeEffect {

        /// <remarks/>
        none,

        /// <remarks/>
        border,

        /// <remarks/>
        shadow,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum FontTypeItalic {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum FontTypeUnderline {

        /// <remarks/>
        yes,

        /// <remarks/>
        no,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum FontTypeWeight {

        /// <remarks/>
        bold,

        /// <remarks/>
        normal,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class TextType {

        private object[] itemsField;

        private string[] textField;

        private TextTypeHalign halignField;

        private decimal hpositionField;

        private TextTypeValign valignField;

        private decimal vpositionField;

        private TextTypeDirection directionField;

        public TextType() {
            this.halignField = TextTypeHalign.center;
            this.hpositionField = ((decimal)(0m));
            this.valignField = TextTypeValign.center;
            this.vpositionField = ((decimal)(0m));
            this.directionField = TextTypeDirection.ltr;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Font", typeof(FontType))]
        [System.Xml.Serialization.XmlElementAttribute("HGroup", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Rotate", typeof(RotateType))]
        [System.Xml.Serialization.XmlElementAttribute("Ruby", typeof(RubyType))]
        [System.Xml.Serialization.XmlElementAttribute("Space", typeof(SpaceType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TextTypeHalign.center)]
        public TextTypeHalign Halign {
            get {
                return this.halignField;
            }
            set {
                this.halignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Hposition {
            get {
                return this.hpositionField;
            }
            set {
                this.hpositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TextTypeValign.center)]
        public TextTypeValign Valign {
            get {
                return this.valignField;
            }
            set {
                this.valignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0")]
        public decimal Vposition {
            get {
                return this.vpositionField;
            }
            set {
                this.vpositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TextTypeDirection.ltr)]
        public TextTypeDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum TextTypeHalign {

        /// <remarks/>
        center,

        /// <remarks/>
        left,

        /// <remarks/>
        right,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum TextTypeValign {

        /// <remarks/>
        center,

        /// <remarks/>
        bottom,

        /// <remarks/>
        top,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public enum TextTypeDirection {

        /// <remarks/>
        ltr,

        /// <remarks/>
        rtl,

        /// <remarks/>
        ttb,

        /// <remarks/>
        btt,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class SubtitleType {

        private object[] itemsField;

        private string spotNumberField;

        private string timeInField;

        private string timeOutField;

        private string fadeUpTimeField;

        private string fadeDownTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Font", typeof(SubtitleTypeFont))]
        [System.Xml.Serialization.XmlElementAttribute("Image", typeof(ImageType))]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(TextType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SpotNumber {
            get {
                return this.spotNumberField;
            }
            set {
                this.spotNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeIn {
            get {
                return this.timeInField;
            }
            set {
                this.timeInField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FadeUpTime {
            get {
                return this.fadeUpTimeField;
            }
            set {
                this.fadeUpTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FadeDownTime {
            get {
                return this.fadeDownTimeField;
            }
            set {
                this.fadeDownTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class SubtitleTypeFont : FontType {

        private TextType[] text1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public TextType[] Text1 {
            get {
                return this.text1Field;
            }
            set {
                this.text1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class scopedTokenType {

        private string scopeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class SubtitleReelTypeLoadFont {

        private string idField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.smpte-ra.org/schemas/428-7/2010/DCST")]
    public partial class SubtitleReelTypeFont : FontType {

        private SubtitleType[] subtitleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subtitle")]
        public SubtitleType[] Subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
    }

}